<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use app\models\Account;
use app\models\Canvasser;
use app\utils\Doubles;
use Yii;
use yii\base\Widget;
use yii\helpers\Html;
use Zelenin\yii\SemanticUI\Elements;

class AccountView extends Widget
{
    /* @var string */
    public $accountId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $account = Account::findOne($this->accountId);
        if ($account == null) {
            return $this->accountId;
        }
        $balance = "";
        if (Doubles::compare($account->balance, 0.0) < 0) {
            $balance = number_format(-$account->balance, 2) . ' ' . Elements::icon('minus square', ['class' => 'red']);
        } else {
            $balance = number_format($account->balance, 2) . ' ' . Elements::icon('add square', ['class' => 'green']);
        }

        return Html::a($account->id, Yii::$app->getUrlManager()->createUrl(['account/ledger', 'id' => $account->id]))." (".$balance.")";
    }


}