<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use app\models\Canvasser;
use Yii;
use yii\base\Widget;

class CollectorView extends Widget
{
    /* @var \app\models\Collector */
    public $collector;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->collector == null) {
            return '<span class="not-set">(not set)</span>';
        }

        $supp = Canvasser::findOne($this->collector);
        if ($supp == null) {
            return '<span class="not-set">(not set)</span>';
        }
        $suppUrl = Yii::$app->getUrlManager()->createUrl(['collector/view', 'id' => $this->collector]);
        $out = '<a href="'.$suppUrl.'" style="color: #1e70bf; margin-right: 20px;"><b>'.$supp->name .'</b></a>';
        return $out;
    }


}