<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use ReflectionClass;
use Yii;
use yii\bootstrap\Html;
use yii\widgets\InputWidget;
use Zelenin\yii\SemanticUI\Elements;
use Zelenin\yii\SemanticUI\modules\Dropdown;
use Zelenin\yii\SemanticUI\modules\Select;
use Zelenin\yii\SemanticUI\widgets\ActiveField;

class CommissionSelector extends InputWidget
{
    public $type_attr;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $attr = $this->type_attr;
        $attr2 = $this->attribute;
        $id = Html::getInputId($this->model, $this->type_attr);
        $id2 = Html::getInputId($this->model, $this->attribute);
        $className = new ReflectionClass($this->model);
        $className = $className->getShortName();
        return Elements::input(
            Html::dropDownList($className.'['.$this->type_attr.']', $this->model->$attr, ["Percentage"=>"Percentage", "Amount" => "Amount"], ['id'=> $id, 'style' => 'width:initial;', 'class' => 'ui selection search','fluid'=>true]) .
            Html::input('number', $className.'['.$this->attribute.']', $this->model->$attr2,  ['id'=> $id2, 'style' => 'display:inline-block;', 'step'=>'0.01']),
            ['class' => 'left action']
        );
    }


}