<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use app\models\Canvasser;
use app\models\HpNewVehicleLoan;
use Yii;
use yii\base\Widget;

class CommissionView extends Widget
{
    /* @var \app\models\HpNewVehicleLoan */
    public $model;

    /* @var number */
    public $type;

    /* @var integer */
    public $owner;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $owner = $this->owner;
        if (!(isset($this->model->$owner)) || $this->model->$owner == null || $this->model->$owner == 0) {
            return '<span class="not-set">(not set)</span>';
        }
        $type = $this->type. "_commision_type";
        $type = $this->model->$type;

        $value = $this->type. "_commision";
        $value = $this->model->$value;

        if ($this->type == 'sales') {
            if ($type == 'Percentage') {
                return "Rs. ".number_format($this->model->getSalesCommission(), 2). " (".$value." %)";
            } else {
                return "Rs. ".number_format($value, 2);
            }
        } else {
            if ($type == 'Percentage') {
                return "Rs. ".number_format($this->model->getCanvassingCommission(), 2). " (".$value." %)";
            } else {
                return "Rs. ".number_format($value, 2);
            }
        }
    }


}