<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use Yii;
use yii\base\Widget;
use yii\bootstrap\Html;

class CustomerView extends Widget
{
    /* @var \app\models\Customer */
    public $customer;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->customer == null) {

            return '<span style="color: red; margin-right: 20px"><i>Not Set</i></span>';
        }
        $customerUrl = Yii::$app->getUrlManager()->createUrl(['customer/view', 'id' => $this->customer->id]);
        $out = '<a href="'.$customerUrl.'" style="color: #1e70bf; margin-right: 20px;"><b>'.$this->customer->name . " (" . $this->customer->nic . ")".'</b></a>';
        return $out;
    }


}