<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use Yii;
use yii\base\Widget;
use yii\bootstrap\Html;

class CustomerView extends Widget
{
    /* @var \app\models\Customer */
    public $customer;

    /* @var boolean */
    public $target = '';

    /* @var string */
    public $fullname = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->customer == null) {

            return '<span class="not-set">(not set)</span>';
        }

        $name = $this->customer->name;
        if ($this->fullname) {
            $name = $this->customer->full_name;
        }
        $customerUrl = Yii::$app->getUrlManager()->createUrl(['customer/view', 'id' => $this->customer->id]);
        $target = '';
        if ($this->target != '') {
            $target = ' target="'.$this->target.'"';
        }
        $out = '<a href="'.$customerUrl.'" '.$target.' style="color: #1e70bf; margin-right: 20px;"><b>'.$name . " (" . $this->customer->nic . ")".'</b></a>';
        return $out;
    }


}