<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use Yii;
use yii\bootstrap\Html;
use yii\widgets\InputWidget;

class CustomerSelector extends InputWidget
{
    /* @var \app\models\Customer */
    public $customer;

    /* @var string */
    public $url;

    /* @var string */
    public $form;

    /* @var string */
    public $remove_url;

    /* @var boolean */
    public $fullname = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $this->getView()->registerJs('
                $( "#csbtn_' . $this->attribute . '" ).click(function() {
                    var datastring = $("#' . $this->form . '").serializeArray();
                    $.post("' . $this->url . '", $.param(datastring), function(data) {
                    
                    });
                });
            ');

        if ($this->customer == null) {

            return '<div style="display: block"><span class="not-set" style="margin-right: 20px;">(not set)</span> '
                . Html::a("Set", '#', ['class' => 'ui button blue', 'id' => 'csbtn_' . $this->attribute]).'</div>';
        }
        $name = $this->customer->name;
        if ($this->fullname) {
            $name = $this->customer->full_name;
        }

        $customerUrl = Yii::$app->getUrlManager()->createUrl(['customer/view', 'id' => $this->customer->id]);
        $out = '<div style="display: block"><a href="'.$customerUrl.'" style="color: #1e70bf; margin-right: 20px;"><b>'.$name . " (" . $this->customer->nic . ")".'</b></a>' . Html::activeHiddenInput($this->model, $this->attribute, ['value' => $this->customer->id])
            . Html::a("Change", '#', ['class' => 'ui button blue', 'id' => 'csbtn_' . $this->attribute]);
        if ($this->remove_url != null) {
            $this->getView()->registerJs('
                $( "#csrbtn_' . $this->attribute . '" ).click(function() {
                    var datastring = $("#' . $this->form . '").serializeArray();
                    $.post("' . $this->remove_url . '", $.param(datastring), function(data) {
                    
                    });
                });
            ');
            $out .= Html::a("Remove", '#', ['class' => 'ui button red', 'id' => 'csrbtn_' . $this->attribute]);
        }
        $out .= '</div>';
        return $out;
    }


}