<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use app\models\Supplier;
use Yii;
use yii\base\Widget;
use yii\bootstrap\Html;

class SupplierView extends Widget
{
    /* @var \app\models\Supplier */
    public $supplier;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->supplier == null) {
            return '<span class="not-set">(not set)</span>';
        }

        $supp = Supplier::findOne($this->supplier);
        if ($supp == null) {
            return '<span class="not-set">(not set)</span>';
        }
        $suppUrl = Yii::$app->getUrlManager()->createUrl(['supplier/view', 'id' => $this->supplier]);
        $out = '<a href="'.$suppUrl.'" style="color: #1e70bf; margin-right: 20px;"><b>'.$supp->name .'</b></a>';
        return $out;
    }


}