<?php
/**
 * Created by PhpStorm.
 * User: Supun
 * Date: 7/12/2017
 * Time: 9:14 PM
 */

namespace app\utils\widgets;


use app\models\Supplier;
use Yii;
use yii\base\Widget;
use yii\bootstrap\Html;

class TxAmountView extends Widget
{
    /* @var \app\models\Transaction */
    public $transaction;

    /* @var string */
    public $account;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->transaction->cr_account === $this->account) {
            return "-".$this->transaction->amount;
        } else {
            return "+".$this->transaction->amount;
        }
    }


}